// Code generated by protoc-gen-go. DO NOT EDIT.
// source: magpie.proto

package magpiepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryType int32

const (
	QueryType_INSERT QueryType = 0
	QueryType_DELETE QueryType = 1
	QueryType_UPDATE QueryType = 2
	QueryType_SELECT QueryType = 3
)

var QueryType_name = map[int32]string{
	0: "INSERT",
	1: "DELETE",
	2: "UPDATE",
	3: "SELECT",
}

var QueryType_value = map[string]int32{
	"INSERT": 0,
	"DELETE": 1,
	"UPDATE": 2,
	"SELECT": 3,
}

func (x QueryType) String() string {
	return proto.EnumName(QueryType_name, int32(x))
}

func (QueryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f97d22a07cda9df9, []int{0}
}

//stream请求结构
type StreamRequest struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f97d22a07cda9df9, []int{0}
}

func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (m *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(m, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type LoadResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartTime            string   `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ElapsedTime          int64    `protobuf:"varint,5,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	RecordCount          int64    `protobuf:"varint,6,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	Message              string   `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadResponse) Reset()         { *m = LoadResponse{} }
func (m *LoadResponse) String() string { return proto.CompactTextString(m) }
func (*LoadResponse) ProtoMessage()    {}
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f97d22a07cda9df9, []int{1}
}

func (m *LoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadResponse.Unmarshal(m, b)
}
func (m *LoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadResponse.Marshal(b, m, deterministic)
}
func (m *LoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadResponse.Merge(m, src)
}
func (m *LoadResponse) XXX_Size() int {
	return xxx_messageInfo_LoadResponse.Size(m)
}
func (m *LoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadResponse proto.InternalMessageInfo

func (m *LoadResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoadResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoadResponse) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *LoadResponse) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *LoadResponse) GetElapsedTime() int64 {
	if m != nil {
		return m.ElapsedTime
	}
	return 0
}

func (m *LoadResponse) GetRecordCount() int64 {
	if m != nil {
		return m.RecordCount
	}
	return 0
}

func (m *LoadResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QueryRequest struct {
	QueryType            QueryType `protobuf:"varint,1,opt,name=QueryType,proto3,enum=QueryType" json:"QueryType,omitempty"`
	Sql                  string    `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f97d22a07cda9df9, []int{2}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetQueryType() QueryType {
	if m != nil {
		return m.QueryType
	}
	return QueryType_INSERT
}

func (m *QueryRequest) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

type QueryResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f97d22a07cda9df9, []int{3}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("QueryType", QueryType_name, QueryType_value)
	proto.RegisterType((*StreamRequest)(nil), "StreamRequest")
	proto.RegisterType((*LoadResponse)(nil), "LoadResponse")
	proto.RegisterType((*QueryRequest)(nil), "QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "QueryResponse")
}

func init() { proto.RegisterFile("magpie.proto", fileDescriptor_f97d22a07cda9df9) }

var fileDescriptor_f97d22a07cda9df9 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x8f, 0xda, 0x30,
	0x14, 0x24, 0x04, 0x92, 0xe6, 0x91, 0xa0, 0xc8, 0xa7, 0x14, 0xa9, 0x12, 0x4d, 0x2f, 0x29, 0x87,
	0x54, 0xa2, 0xc7, 0x9e, 0x5a, 0xf0, 0xa1, 0x2b, 0x76, 0xb5, 0x84, 0xec, 0x65, 0x2f, 0xc8, 0x24,
	0x4f, 0x08, 0x89, 0x7c, 0x10, 0x3b, 0xd2, 0xf2, 0x2f, 0xf7, 0x27, 0xad, 0xec, 0x04, 0x08, 0x97,
	0xbd, 0x8d, 0x67, 0x9e, 0xad, 0x37, 0x33, 0x06, 0x3b, 0x63, 0xfb, 0xf2, 0x80, 0x61, 0x59, 0x15,
	0xa2, 0xf0, 0x7f, 0x80, 0xb3, 0x11, 0x15, 0xb2, 0x2c, 0xc2, 0x53, 0x8d, 0x5c, 0x10, 0x02, 0x83,
	0x94, 0x09, 0xe6, 0x69, 0x53, 0x2d, 0xb0, 0x22, 0x85, 0xfd, 0x77, 0x0d, 0xec, 0x55, 0xc1, 0xd2,
	0x08, 0x79, 0x59, 0xe4, 0x1c, 0xe5, 0x50, 0x52, 0xa4, 0xa8, 0x86, 0x86, 0x91, 0xc2, 0x92, 0xcb,
	0x59, 0x86, 0x5e, 0xbf, 0xb9, 0x28, 0x31, 0xf9, 0x06, 0xc0, 0x05, 0xab, 0xc4, 0x56, 0x1c, 0x32,
	0xf4, 0x74, 0xa5, 0x58, 0x8a, 0x89, 0x0f, 0x19, 0x92, 0xaf, 0xf0, 0x05, 0xf3, 0xb4, 0x11, 0x07,
	0x4a, 0x34, 0x31, 0x4f, 0x95, 0xf4, 0x1d, 0x6c, 0x3c, 0xb2, 0x92, 0x63, 0x2b, 0x0f, 0xa7, 0x5a,
	0xa0, 0x47, 0xa3, 0x96, 0xbb, 0x8c, 0x54, 0x98, 0x14, 0x55, 0xba, 0x4d, 0x8a, 0x3a, 0x17, 0x9e,
	0xd1, 0x8c, 0x34, 0xdc, 0x42, 0x52, 0xc4, 0x03, 0x33, 0x43, 0xce, 0xd9, 0x1e, 0x3d, 0xb3, 0x79,
	0xbf, 0x3d, 0xfa, 0x0f, 0x60, 0xaf, 0x6b, 0xac, 0xce, 0x17, 0xdb, 0x01, 0x58, 0xea, 0x1c, 0x9f,
	0xcb, 0xc6, 0xd6, 0x78, 0x0e, 0xe1, 0x95, 0x89, 0x6e, 0x22, 0x71, 0x41, 0xe7, 0xa7, 0x63, 0x6b,
	0x53, 0x42, 0x7f, 0x0d, 0x4e, 0xfb, 0xd6, 0x27, 0xf1, 0x74, 0x56, 0xe9, 0xdf, 0xad, 0x72, 0x4d,
	0x5c, 0xbf, 0x25, 0x3e, 0xfb, 0xd3, 0x59, 0x87, 0x00, 0x18, 0xff, 0x9f, 0x36, 0x34, 0x8a, 0xdd,
	0x9e, 0xc4, 0x4b, 0xba, 0xa2, 0x31, 0x75, 0x35, 0x89, 0x5f, 0x9e, 0x97, 0x7f, 0x63, 0xea, 0xf6,
	0x25, 0xde, 0xd0, 0x15, 0x5d, 0xc4, 0xae, 0x3e, 0xdf, 0x82, 0xf1, 0xa8, 0x3a, 0x26, 0x3f, 0x61,
	0x20, 0x7b, 0x23, 0xe3, 0xf0, 0xae, 0xe4, 0x89, 0x13, 0x76, 0xeb, 0xf4, 0x7b, 0x81, 0x46, 0x66,
	0x60, 0xd2, 0x37, 0x4c, 0x6a, 0x81, 0xc4, 0x09, 0xbb, 0xd1, 0x4c, 0xc6, 0xe1, 0x9d, 0x3b, 0xbf,
	0xf7, 0x6f, 0xf4, 0x6a, 0xfd, 0x6a, 0x7e, 0x51, 0xb9, 0xdb, 0x19, 0xea, 0x23, 0xfd, 0xfe, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xa1, 0xf7, 0x72, 0xaa, 0x58, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MagpieClient is the client API for Magpie service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MagpieClient interface {
	Load(ctx context.Context, opts ...grpc.CallOption) (Magpie_LoadClient, error)
	Execute(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type magpieClient struct {
	cc *grpc.ClientConn
}

func NewMagpieClient(cc *grpc.ClientConn) MagpieClient {
	return &magpieClient{cc}
}

func (c *magpieClient) Load(ctx context.Context, opts ...grpc.CallOption) (Magpie_LoadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Magpie_serviceDesc.Streams[0], "/Magpie/Load", opts...)
	if err != nil {
		return nil, err
	}
	x := &magpieLoadClient{stream}
	return x, nil
}

type Magpie_LoadClient interface {
	Send(*StreamRequest) error
	CloseAndRecv() (*LoadResponse, error)
	grpc.ClientStream
}

type magpieLoadClient struct {
	grpc.ClientStream
}

func (x *magpieLoadClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *magpieLoadClient) CloseAndRecv() (*LoadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LoadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *magpieClient) Execute(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/Magpie/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MagpieServer is the server API for Magpie service.
type MagpieServer interface {
	Load(Magpie_LoadServer) error
	Execute(context.Context, *QueryRequest) (*QueryResponse, error)
}

// UnimplementedMagpieServer can be embedded to have forward compatible implementations.
type UnimplementedMagpieServer struct {
}

func (*UnimplementedMagpieServer) Load(srv Magpie_LoadServer) error {
	return status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (*UnimplementedMagpieServer) Execute(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}

func RegisterMagpieServer(s *grpc.Server, srv MagpieServer) {
	s.RegisterService(&_Magpie_serviceDesc, srv)
}

func _Magpie_Load_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MagpieServer).Load(&magpieLoadServer{stream})
}

type Magpie_LoadServer interface {
	SendAndClose(*LoadResponse) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type magpieLoadServer struct {
	grpc.ServerStream
}

func (x *magpieLoadServer) SendAndClose(m *LoadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *magpieLoadServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Magpie_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagpieServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Magpie/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagpieServer).Execute(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Magpie_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Magpie",
	HandlerType: (*MagpieServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _Magpie_Execute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Load",
			Handler:       _Magpie_Load_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "magpie.proto",
}
